### ISSUE TITLE
Inconsistent default value of parameter for GET http://urcodebin.live/paste/public

### ISSUE THREAD

**Issue by nntzuekai** [Mathew-Estafanous/Ur-Codebin-API#11]
Hello, 

I discovered an inconsistency between the default value of the **paste_title** query parameter in code (https://github.com/Mathew-Estafanous/Ur-Codebin-API/blob/main/src/main/java/com/urcodebin/api/controllers/CodePasteController.java#L60) , which is "" (empty string) and in the specification (https://mathew.stoplight.io/docs/ur-codebin-api/b3A6NDIxNTk5Mg-get-search-for-public-code-pastes), which is " " (space). 

Can you please  check and confirm which of the two, code or spec is correct? 

Thanks.

**Comment by Mathew-Estafanous** [comment]
Hi!

Follow the code of `””`. The documentation is incorrect.

**Comment by nntzuekai** [comment]
Hi,

Thank you for confirming this!
